ALTER TABLE role_permissions 
MODIFY COLUMN module enum('ACTION_MANAGEMENT','AUDIT_LOGS','BOARD','BOM','CHANGE_PROTOCOL',
'DASHBOARD','FB_FAMILY','INVENTORY','KPIS','MAINTENANCE','MAINTENANCE_SCHEDULE',
'PACK','PHASE','PROJECT','ROLE','SITE','USER','USERS_PREVENTIVE','WEEKLY_REPORT','Custom') NOT NULL;